include:
  - project: 'isinkare/acc-py-devtools'
    ref: feature/prevent-fork-jobs
    file: 'acc_py_devtools/templates/gitlab-ci/python.yml'

stages:
  - Code Quality

variables:
  ACCPY_PYQT_DOCKER_IMAGE: gitlab-registry.cern.ch/acc-co/devops/python/distribution/ci/pyqt:v2020-11rc2
  project_name: accwidgets  # Required by acc-py templates
  PY_VERSION: "3.7"  # Set expectations of the base templates to our assumed Python version

.init_sequence: &init_sequence
- git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cern.ch".insteadOf ssh://git@gitlab.cern.ch:7999

before_script:
  - *init_sequence
  - env

run in all:
  stage: Code Quality
  script:
    - echo "I run in all"

run in both:
  stage: Code Quality
  extends: .acc_py_only_on_primary_repo
  script:
    - echo "I run in both"

run in both 2:
  stage: Code Quality
  extends: .acc_py_only_on_primary_repo
  variables:
    ACC_PY_PRIMARY_NS: ""
  script:
    - echo "I run in both"

run in main:
  stage: Code Quality
  extends: .acc_py_only_on_primary_repo
  variables:
    ACC_PY_PRIMARY_NS: "acc-co/accsoft/gui"
  script:
    - echo "I run in main"

.conditional:
  rules:
    - if: '$CONDITION'

run in main with condition true:
  stage: Code Quality
  extends:
    - .acc_py_only_on_primary_repo
    - .conditional
  variables:
    ACC_PY_PRIMARY_NS: "acc-co/accsoft/gui"
    CONDITION: 1
  script:
    - echo "I run in main"

run in main with condition false:
  stage: Code Quality
  extends:
    - .acc_py_only_on_primary_repo
    - .conditional
  variables:
    ACC_PY_PRIMARY_NS: "acc-co/accsoft/gui"
    CONDITION: 0
  script:
    - echo "I do NOT run in any"

run in both in condition true:
  stage: Code Quality
  extends:
    - .acc_py_only_on_primary_repo
    - .conditional
  variables:
    CONDITION: 1
  script:
    - echo "I run in both"

run in both in condition false:
  stage: Code Quality
  extends:
    - .acc_py_only_on_primary_repo
    - .conditional
  variables:
    CONDITION: 0
  script:
    - echo "I do NOT run in any"