include:
  - project: 'acc-co/devops/python/acc-py-devtools'
    file: 'acc_py_devtools/templates/gitlab-ci/python.yml'


stages:
  - Code Quality
  - Source Tests
  - Build Wheel
  - Wheel Tests
  - Documentation
  - Upload Release

variables:
  ACCPY_IMAGE_CC7_2020_11: registry.cern.ch/acc/acc-py_cc7_openjdk11_gui_ci:2020.11
  ACCPY_IMAGE_CC7_2021_12: registry.cern.ch/acc/acc-py_cc7_openjdk11_gui_ci:2021.12
  ACCPY_IMAGE_CS8_2020_11: registry.cern.ch/acc/acc-py_cs8_openjdk11_gui_ci:2020.11
  ACCPY_IMAGE_CS8_2021_12: registry.cern.ch/acc/acc-py_cs8_openjdk11_gui_ci:2021.12
  ACCPY_IMAGE_INFRASTRUCTURE: registry.cern.ch/acc/acc-py_cc7_openjdk11_gui_ci:pro
  project_name: accwidgets  # Required by acc-py templates

.init_sequence: &init_sequence
- git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cern.ch".insteadOf ssh://git@gitlab.cern.ch:7999
- pip install -U pip

before_script:
  - *init_sequence

.matrix_job:
  image: $CURRENT_BASE_IMAGE
  parallel:
    matrix:
      - CURRENT_BASE_IMAGE: $ACCPY_IMAGE_CC7_2020_11
      - CURRENT_BASE_IMAGE: $ACCPY_IMAGE_CC7_2021_12
      - CURRENT_BASE_IMAGE: $ACCPY_IMAGE_CS8_2020_11
      - CURRENT_BASE_IMAGE: $ACCPY_IMAGE_CS8_2021_12

flake8:
  extends: .matrix_job
  stage: Code Quality
  script:
    - pip install .[lint]
    - export LANG=en_US.UTF-8  # Otherwise, flake8 might fail with UnicodeDecodeError: 'ascii' codec can't decode byte
    - flake8

mypy:
  extends: .matrix_job
  stage: Code Quality
  script:
    - pip install -e .[lint]
    - mypy .

pre-commit:
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Code Quality
  script:
    - pip install -e .[lint]
   # Run pre-commit on the changes. If in MR form, we run for all commits in the MR,
   # otherwise just on the last commit.
    - pre-commit run --from-ref ${CI_MERGE_REQUEST_DIFF_BASE_SHA:-HEAD~1} --to-ref $CI_COMMIT_SHA

pytest:
  extends: .matrix_job
  stage: Source Tests
  script:
    - |
      pip install .[test]
      extra_args=
      [[ "$CURRENT_BASE_IMAGE" == "$ACCPY_IMAGE_CC7_2020_11" ]] && extra_args="--cov-report html:coverage --cov-report xml:cobertura.xml --cov-report term-missing:skip-covered --cov=accwidgets"
      OMP_NUM_THREADS=1 run_headless python -m pytest --random-order --junitxml=report.xml $extra_args -vx --color=yes tests/
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    name: coverage-report
    paths:
      - coverage
    when: on_success
    expire_in: 1 month
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

.aux_install_extras:
  variables:
    AUX_EXTRAS: all-widgets,test,lint,doc,examples,bench

test aux dep collisions:
  extends: .aux_install_extras
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Source Tests
  script:
    - pip install .[$AUX_EXTRAS]

build wheel:
  extends: .acc_py_build_wheel
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Build Wheel

.inspect_install_extras:
  extends: .aux_install_extras
  stage: Wheel Tests
  before_script:
    - *init_sequence
    - pip install importlib_metadata
    - pip install ./wheelhouse/*.whl
    - export WIDGET_EXTRAS=$(python -c "from importlib_metadata import metadata; print(','.join(set(metadata('accwidgets').json['provides_extra']) - ({'all'} | set('$AUX_EXTRAS'.split(',')))))")

test imports:
  extends: .inspect_install_extras
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  script:
    # As of today, Gitlab CI does not support variable expansion in parallel:matrix,
    # therefore we're force to keep an internal loop inside a single job instead of
    # having 1 job per installation variant.
    # https://gitlab.com/gitlab-org/gitlab/-/issues/11549
    - IFS=, EXTRAS_ARRAY=( $WIDGET_EXTRAS )
    - WHEEL_PATH=$(realpath ./wheelhouse/*.whl)
    - |
      for extra in "${EXTRAS_ARRAY[@]}"; do
          acc-py venv .job-venv
          echo "Installing $extra"
          bash -c "source .job-venv/bin/activate && pip install $WHEEL_PATH[$extra] && echo 'Running Python import' && python -c 'import accwidgets.$extra'"
          rm -rf .job-venv
      done

test dep collisions:
  extends:
    - .inspect_install_extras
    - .matrix_job
  image: $CURRENT_BASE_IMAGE
  script:
    - |
      echo "Installing categories: $WIDGET_EXTRAS"
      pip install .[$WIDGET_EXTRAS]

.sphinx_custom:
  stage: Documentation
  before_script:
      - *init_sequence
      - yum install -y -q graphviz  # Required to generate inheritance diagrams
      - pip install .[doc]  # Need to install it here, as sphobjinv should be available
      - python -c "import sphobjinv as soi; [soi.fileops.writebytes(path=f'docs/{f}.inv', contents=soi.zlib.compress(soi.Inventory(plaintext=soi.fileops.readbytes(f'docs/{f}.txt')).data_file())) for f in ['qt', 'pyqt', 'pjlsa']]" # Prepare custom intersphinx inventory files

sphinx:
  extends:
    - .acc_py_build_docs
    - .sphinx_custom
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  only:
    refs:
      - master
      - develop

sphinx on tag:
  extends:
    - .acc_py_build_docs_on_tag_v2
    - .sphinx_custom
  image: $ACCPY_IMAGE_INFRASTRUCTURE

release wheel on tag:
  extends: .acc_py_release_wheel
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Upload Release

release sdist on tag:
  extends: .acc_py_release_sdist_v2
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Upload Release

anybadge:
  image: $ACCPY_IMAGE_INFRASTRUCTURE
  stage: Documentation
  script:
    - pip install anybadge
    - pip install .[lint,doc]
    - mkdir -p badges
    - BADGE_MYPY_VERSION="$(read -a mypy_output <<< "$(pip list | grep -E mypy[\t\ ])" && echo ${mypy_output[1]})"
    - BADGE_FLAKE8_VERSION="$(read -a flake8_output <<< "$(pip list | grep -E flake8[\t\ ])" && echo ${flake8_output[1]})"
    - BADGE_SPHINX_VERSION="$(read -a sphinx_output <<< "$(pip list | grep -E Sphinx[\t\ ])" && echo ${sphinx_output[1]})"
    - BADGE_ACCWIDGETS_VERSION="$(python -c 'import accwidgets; print(accwidgets.__version__)' | awk '{split($0,ver,"+");print ver[1]}')"
    - anybadge -l mypy -v "v${BADGE_MYPY_VERSION}" -f badges/mypy.svg -c olive -o
    - anybadge -l flake8 -v "v${BADGE_FLAKE8_VERSION}" -f badges/flake8.svg -c olive -o
    - anybadge -l acc-py-repo -v "accwidgets v${BADGE_ACCWIDGETS_VERSION}" -f badges/repo.svg -c purple -o
    - anybadge -l documentation -v "sphinx v${BADGE_SPHINX_VERSION}" -f badges/docs.svg -c teal -o
  artifacts:
    paths:
      - badges
    when: on_success
    expire_in: 1 day
  only:
    refs:
      - develop
